---

- name: Apache2 | php.ini configuration.
  ini_file: >
    dest="{{ hwr_path_php_ini_apache }}"
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items: php_ini
